# Generated by Django 2.1.4 on 2018-12-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.IntegerField(default=1, verbose_name='test/comfig')),
                ('name', models.CharField(max_length=50, verbose_name='用例/配置名称')),
                ('belong_project', models.CharField(max_length=50, verbose_name='所属项目')),
                ('include', models.CharField(max_length=1024, verbose_name='前置config/test')),
                ('author', models.CharField(max_length=20, verbose_name='编写人员')),
                ('request', models.TextField(verbose_name='请求信息')),
            ],
            options={
                'verbose_name': '用例信息',
                'db_table': 'TestCaseInfo',
            },
        ),
        migrations.CreateModel(
            name='TestReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('report_name', models.CharField(max_length=40)),
                ('start_at', models.CharField(max_length=40, null=True)),
                ('status', models.BooleanField()),
                ('testsRun', models.IntegerField()),
                ('successes', models.IntegerField()),
                ('reports', models.TextField()),
            ],
            options={
                'verbose_name': '测试报告',
                'db_table': 'TestReports',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('status', models.IntegerField(default=1, verbose_name='有效/无效')),
            ],
            options={
                'verbose_name': '用户信息',
                'db_table': 'UserInfo',
            },
        ),
    ]
